service:
  name: serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: 'DEV'
  environment: ${file(serverless-env.yml):${self:provider.stage}}

functions:
  graphql:
    handler: src/graphql/graphql.graphqlHandler
    events:
      - http:
          method: post
          path: /
  # getCustomers:
  #   handler: src/handlers/customer/get-all.action
  #   events:
  #     - httpApi:
  #         method: post
  #         path: /customer/getAll
  # createCustomer:
  #   handler: src/handlers/customer/create.action
  #   events:
  #     - httpApi:
  #         method: post
  #         path: /customer/create
  # updateCustomer:
  #   handler: src/handlers/customer/update.action
  #   events:
  #     - httpApi:
  #         method: post
  #         path: /customer/update
  # deleteCustomer:
  #   handler: src/handlers/customer/delete.action
  #   events:
  #     - httpApi:
  #         method: delete
  #         path: /customer/{id}
  
